stages:
  - build
  - deploy

variables:
  VITE_APP_BASE_URL: $VITE_APP_BASE_URL
  VITE_GOOGLE_AUTH_URL: $VITE_GOOGLE_AUTH_URL

build_project:
  stage: build
  image: node:lts
  script:
    - echo "의존성 설치 및 빌드 시작"
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
  tags:
    - frontend

deploy_to_vm:
  stage: deploy
  image: alpine:latest
  script:
    - echo "배포 중"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "StrictHostKeyChecking no" > ~/.ssh/config
    - scp -r dist/* kdt@34.47.79.162:/home/kdt/front/
    - ssh kdt@34.47.79.162 'sudo systemctl restart nginx'
  tags:
    - frontend
  only:
    - master
