stages:
  - install
  - build
  - deploy

install_dependencies:
  stage: install
  image: node:lts
  script:
    - echo "의존성 설치 중"
    - npm ci
  artifacts:
    paths:
      - node_modules/
  tags:
    - frontend

build_project:
  stage: build
  image: node:lts
  script:
    - echo "프로젝트 빌드 중"
    - npm run build
  artifacts:
    paths:
      - dist/
  tags:
    - frontend

deploy_to_vm:
  stage: deploy
  script:
    - echo "배포 중"
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "StrictHostKeyChecking no" > ~/.ssh/config
    - scp -r dist/* kdt@34.47.79.162:/home/kdt/front/
    - ssh kdt@34.47.79.162 'sudo systemctl restart nginx'
  tags:
    - frontend
  only:
    - master
